# Generated by Django 3.0.8 on 2020-07-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companylogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Region')),
            ],
        ),
        migrations.CreateModel(
            name='ViewTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('street_only', models.CharField(max_length=100, null=True)),
                ('home', models.CharField(max_length=5, null=True)),
                ('flat', models.CharField(max_length=5, null=True)),
                ('phone', models.CharField(max_length=5, null=True)),
                ('logins', models.CharField(max_length=15, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('companylogin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Companylogin')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Priority')),
                ('regions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Region')),
                ('streets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Street')),
                ('viewticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.ViewTicket')),
            ],
        ),
    ]
