# Generated by Django 3.0.8 on 2020-07-31 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tk', '0002_auto_20200730_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастера', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date'], 'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='street',
            name='region',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Region', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='companylogin',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Companylogin', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flat',
            field=models.CharField(max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='home',
            field=models.CharField(max_length=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='logins',
            field=models.CharField(max_length=15, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='master',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Master', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Priority', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='regions',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Region', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='street_only',
            field=models.CharField(blank=True, default='ничего нет', max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='streets',
            field=models.ForeignKey(blank=True, default='ничего нет', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Street', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='viewticket',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tk.ViewTicket', verbose_name=''),
        ),
    ]
