# Generated by Django 3.0.8 on 2020-08-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tk', '0005_auto_20200801_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='comment',
            new_name='coment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Ticket', verbose_name=''),
        ),
    ]
