# Generated by Django 3.0.8 on 2020-08-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk', '0006_auto_20200801_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
