# Generated by Django 3.0.8 on 2020-08-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tk', '0008_auto_20200803_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment_master',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Priority', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tk.Status', verbose_name='Статус'),
        ),
    ]
