# Generated by Django 3.0.8 on 2020-08-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk', '0009_auto_20200803_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='coment',
            field=models.TextField(blank=True, default='Нет комментария', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comment_master',
            field=models.TextField(blank=True, default='Нет комментария', null=True, verbose_name='Комментарий'),
        ),
    ]
