# Generated by Django 3.0.8 on 2020-08-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('tk', '0011_auto_20200803_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Группа'),
        ),
    ]
